title: Ronak Narkhede
email: ronaknar2001@gmail.com
url: https://ronaknarkhede.github.io
baseurl: ""

# Social media links
github_username:  ronsys11
linkedin_username: ronak-narkhede

markdown: kramdown
# ins_logo: "./bits-logo.png"

# Build settings
remote_theme: jekyll/minima
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

collections:
  projects:
    output: true
    order:
      - test.md

minima:
  date_format: "%b %-d, %Y"
  skin: auto
  
google_analytics: G-YY5TFPFSPX

nav:
 - name: "Resume"
   link: "cv.pdf"
